# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path.

name: Maven Package

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Determine next version
      uses: gps/determine-next-version@master
      id: next_version
      with:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_PREFIX: v
        
    - name: Tag commit
      uses: gps/tag-commit@master
      with:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: ${{steps.next_version.outputs.NEXT_BUILD_VERSION}}
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      
    - name: Create release
      uses: gps/create-github-release@master
      with:
       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       TAG_NAME: ${{ github.ref }}
       ARTIFACTS: |
        dist/foo ==> foo
        dist/bar ==> bar
      env:
        GITHUB_TOKEN: ${{ github.token }}
